### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by warp9pnt9** [Munawwar/flex-helper#1]
First of all, thank you for the creation of this library.  I am a XUL expat, a refugee of a deprecated technology soon to be obsoleted, trying to make my way in an untamed world of WebExtensions.  Having vbox and hbox emulation in pure CSS, with generic and robust classes, so concisely and thoroughly defined as you have done, shall prove most helpful!

But what about the license or any attribution conditions or requests?  Even if you wish to have no license (public domain), it should be stated in the README.md.  I'd like to use this CSS (or any modified versions) with some add-on code released under the Mozilla Public License 2.0, giving credit to Munawwar at the URI https://github.com/Munawwar/flex-helper , at the least in my own README file in an ATTRIBUTIONS section, and possibly within the user interface of the add-on i.e. on an "About" page.

**Comment by Munawwar** [comment]
Done. MIT license like my other projects.

**Comment by warp9pnt9** [comment]
Cool!  I just put a comment block at the top of the css file.

```
/*
 * flex-helper
 * Copyright (c) 2017 Munawwar
 * Released under the MIT License
 * https://github.com/Munawwar/flex-helper
 */
```

I've mentioned this little CSS lib on in a JSFiddle which I linked from a StackOverflow and a MozillaZine post.  These included an earlier version of comment.

**Comment by Munawwar** [comment]
Hah, I found your post at MozillaZine - http://forums.mozillazine.org/viewtopic.php?f=19&t=2969873.
Coincidentally the OP posted the question the very day I created flex-helper.
